# The base path where the dataframes will be stored

base_path : "/ptmp/mpa/ivkos/outflows"
tng_datapath: "/virgotng/universe/IllustrisTNG/"
sim_name: "L35n2160TNG"

# sim_name: "L75n1820TNG"
merger_history_path : "/virgotng/universe/IllustrisTNG/L35n2160TNG/postprocessing/trees/SubLink_gal/tree_extended.hdf5"
hdf_key: "galaxies"

# Directory prefixes where dataframes will be stored should get the snap number attached
dir_prefix : 'snap_'

# Dataframe prefix should also get the snap_number attached to it
df_name : 'testing_df_'

# file endings
hdf_ending : '.hdf5'

# scale that should be cutout relative to the virial radius
cutout_scale : '1.1' 